CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID          VARCHAR(20) PRIMARY KEY,
    USER_ID             VARCHAR(20) NOT NULL,
    STATUS              VARCHAR(30) NOT NULL,
    PAYMENT_TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
    APPROVAL_NUMBER     VARCHAR(39) NOT NULL,
    MERCHANT_ID         VARCHAR(20) NOT NULL,
    METHOD              VARCHAR(30) NOT NULL,
    CURRENCY            VARCHAR(3) NOT NULL,
    AMOUNT              DECIMAL(19, 2) NOT NULL,
    Fees                JSON NOT NULL,
    DETAILS             JSON NOT NULL,
    REGISTERED_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS MERCHANTS (
    MERCHANT_ID         VARCHAR(20) PRIMARY KEY,
    FIXED_AMOUNT_FEES   JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS WALLETS (
    WALLET_ID           VARCHAR(20) PRIMARY KEY,
    USER_ID             VARCHAR(20) UNIQUE,
    BALANCES            JSON NOT NULL,
    REGISTERED_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    LAST_TIMESTAMP      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
